--- #YAML:1.0
name:               AnyEvent-HTTPD-SendMultiHeaderPatch
version:            v0.1.1
abstract:           ~
author:
    - Cindy Wang (CindyLinz)
license:            Artistic_2_0
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    AnyEvent::HTTPD:  0
    Test::More:       0
    version:          0
requires:
    perl:  5.006
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
